// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var XhrHtml = require("./Xhr.html");

var XHR = /* module */[];

var xhr = new XMLHttpRequest();

xhr.open("GET", "http://google.com", true);

xhr.send();

console.log("text");

console.log(xhr);

exports.XHR = XHR;
exports.xhr = xhr;
/*  Not a pure module */
